### ISSUE TITLE
Strange behavior in implementing unit test with false result 

### ISSUE THREAD

**Issue by toor1245** [Noxious-Raccoons/UnicodeValidator.Net#3]
When we run unit tests where the expected result must be `false` we obtain 
```C#
UnicodeValidator.UnitTests.Utf8ValidatorTests.TestUtf8_AssertMustBeMatchExpectedResult("~АḂⲤ𝗗𝖤𝗙ꞠꓧȊ𝐉𝜥ꓡ𝑀𝑵Ǭ𝙿𝑄Ŗ𝑆𝒯𝖴𝘝𝘞ꓫŸ𝜡ả𝘢ƀ𝖼ḋếᵮℊ𝙝Ꭵ𝕛кιṃդⱺ𝓅𝘲𝕣𝖘ŧ𝑢ṽẉ𝘅ყž1234567890!@#$%^&*()-")

Test not run
```
and marked like `Inconclusive test` with successfully passed
and when we set the expected result `true` for expected `false` result we get 
```c#
One or more child tests had errors
The exception doesn`t have a stack trace
```

**Comment by Dilorfin** [comment]
It's not an issue. At least, it's not our issue. 
https://resharper-support.jetbrains.com/hc/en-us/community/posts/360009533600-Debug-test-results-in-Inconclusive-Test-not-run-

Using dotnet CLI or VS2019 "Test Explorer" all tests run correctly:

![image](https://user-images.githubusercontent.com/19252020/104007028-f7981d00-51af-11eb-8559-c066a9f27117.png)
![image](https://user-images.githubusercontent.com/19252020/104007422-93298d80-51b0-11eb-84be-09878cae9e26.png)

Also this test runs correctly using JetBrains UI's (Rider or ReSharper) in case of creating separated tests like this:
![image](https://user-images.githubusercontent.com/19252020/104007832-3c708380-51b1-11eb-8d17-6021273aace2.png)

**Comment by toor1245** [comment]
Thanks
